### PR TITLE
Add support for maintenance notification

### PR DESCRIPTION
**Pull request by rvsit**
As Osiris now shows a maintenance notification, I added support for it

### CODE REVIEW

**Comment by christiaangoossens** [comment]
@royvs33 Seems nice! I see one thing I would like to change: you can use a variable for the Osiris URL in your new code.

Also, I found that this script crashed randomly sometimes when running as a daemon in the background. Did you encounter this as well?

**Comment by rvsit** [comment]
Yes, currently testing a version that resets the session when it gets a "bad request" response

I did indeed forgot to change the URL to a variable

**Comment by christiaangoossens** [comment]
I will wait for an update to this PR then. Thanks! :+1: 
I gave up temporarily on working on this when it timed out after a few hours, because of a lack of time.

**Comment by christiaangoossens** [comment]
@royvs33 Do you have an update?

**Comment by rvsit** [comment]
Did not really look at it anymore, because all my grades are live already, you could close this pr, I will come back to it sometime probably

**Comment by christiaangoossens** [comment]
I will merge it and fix the issue myself then, thanks for contributing.

**Pull request merged**
